twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@TalesFromADevFlowbite/form/default.html.twig'

    globals:
        siteInfo: '@App\Twig\Extension\SiteExtension'
        siteBaseUrl: '%env(SITE_BASE_URL)%'
    paths:
        '%kernel.project_dir%/public/images': images

when@test:
    twig:
        strict_variables: true
